### ISSUE TITLE
Investigate the possibility of using Chrome in headless mode

### ISSUE THREAD

**Issue by clebert** [clebert/cybernaut#110]
https://www.chromestatus.com/features/5678767817097216
https://news.ycombinator.com/item?id=14101233

**Comment by clebert** [comment]
--js-flags="--max_old_space_size=500"

https://news.ycombinator.com/item?id=14104359

**Comment by timbru31** [comment]
FYI, Chrome headless does not work with Selenium yet:
https://bugs.chromium.org/p/chromium/issues/detail?id=604324

**Comment by clebert** [comment]
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by clebert** [comment]
https://developers.google.com/web/updates/2017/04/headless-chrome#drivers
