### ISSUE TITLE
Readme is too long

### ISSUE THREAD

**Issue by unstubbable** [clebert/cybernaut#137]
Consider extracting the API Documentation and maybe also "Testing with Docker" as well as "Emulating mobile devices in Chrome" into separate docs.

**Comment by clebert** [comment]
I'm thinking about adding these parts to the GitHub Wiki. What do you think?

**Comment by unstubbable** [comment]
Either that or you could use https://www.gitbook.com, see http://redux.js.org for example.

**Comment by clebert** [comment]
Good idea, I will try it!

**Comment by clebert** [comment]
I have now restructured the README and published it as a gitbook: https://clebert.gitbooks.io/cybernaut/

A custom domain has already been requested: cybernaut.js.org

What do you think? Any suggestions for improvement?

**Comment by unstubbable** [comment]
Awesome! 🎉

(fixed with #143)
