### ISSUE TITLE
Support parallel testing by using multiple docker containers

### ISSUE THREAD

**Issue by ghost** [clebert/cybernaut#266]
`Proposal|Feature:` It would be nice to run multiple docker containers in parallel, to allow testing of different test cases in a short amount of time.

This is not a direct feature of cybernaut itself, but since docker is supported, it would be great to have this.

**Comment by clebert** [comment]
It is already possible to start any number of parallel docker containers. In addition, Cybernaut still has the ability to parallel the tests in a Docker container, please see the `concurrency` config option: https://cybernaut.js.org/docs/overview/configuring-cybernaut.html
